version: '3.8'

services:
  web:
    build: .
    ports:
      - "8820:8820"
    volumes:
      - ./data:/app/data
      - ./questions:/app/questions
      - ./answers:/app/answers
      - ./backups:/app/backups
      - ./state.json:/app/state.json
    environment:
      - NODE_ENV=production
    depends_on:
      - core
    networks:
      - qnacf-network

  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    volumes:
      - ./data:/app/data
      - ./questions:/app/questions
      - ./answers:/app/answers
      - ./backups:/app/backups
      - ./state.json:/app/state.json
    networks:
      - qnacf-network
    command: ["tail", "-f", "/dev/null"]  # Держать контейнер запущенным

networks:
  qnacf-network:
    driver: bridge

volumes:
  data:
